exports.Userdetails=[
    {
        loginName:'19925956050',
        userDetail:{
            Git:'https://github.com/linyangcong',
            Wanted:'Web前端开发',
            Name:'林养从',
            Born:'1993.10.04',
            Nation:'汉族',
            Height:'170',
            Mobile:'19925956050',
            PoliticalIdentity:'群众',
            Email:'linyc_gd@163.com',
            GraduatedSchool:'广东南方职业学院',
            Education:'大专',
            HomeAddress:'广东省普宁市',
            Profession:'软件技术',
            EducationBackground:{
                FromDate:'2015.09',
                ToDate:'2018.06',
                SchoolName:'广东南方职业学院',
                MajorSubject:'C语言,C++,Java,C#,PHP,网页设计,数据结构,SQL,Mysql,Java GUI,软件测试,软件工程,JSP,Photoshop,Linux,Flash，计算机网络基础等',
                SelfCourse:'ReactJS,VueJS,JqueryJS,ES6语法,NodeJS,WebPack配置,BabelJS配置,Electron桌面端部署,HTML5,微信小程序,Nginx服务器配置,ELK(Elasticsearch,Logstash,Kibana),Zookeeper,ReactNative,Android'
            },
            InternshipExperience:[
                {
                FromDate:'2017.06',
                ToDate:'2017.11',
                CompanyName:'广东源酷科技有限公司',
                Position:'前端实习生',
                DoWhat:''
                },
                {
                    FromDate:'2017.11',
                    ToDate:'2018.05',
                    CompanyName:'创业慧康科技股份有限公司',
                    Position:'试用期前端兼实施',
                    DoWhat:'新系统上线远程培训推广推广;系统更新、运行维护测试;App各个android市场的发布;解决用户反馈的前端以及数据问题'
                },
                {
                    FromDate:'2018.06',
                    ToDate:'现在',
                    CompanyName:'创业慧康科技股份有限公司',
                    Position:'前端',
                    DoWhat:'二次开发公司系统'
                }
            ],
            CampusExperience:[
                {
                    Date:'2017.09',
                    DoWhat:'帮助学校编写并搭建精品课程网站，学校官网的一部分,人力资源管理（https://www.gdnfu.com/a/jingpinkecheng/）'
                },
                {
                    Date:'2017.05-2017.10',
                    DoWhat:'协助导师开发电池检测系统，主要配合Servlet展示JSP页面'
                },
            ],
            personalWorks:[
               {
                FromDate:'2018.06',
                ToDate:'2018.07',
                DoWhat:'居家养老平台前端',
                Github:['https://github.com/linyangcong/HomeCare'],
                UseTec:'ReactJS,react-amap,react-router,ES6,antd,geocoder,BabelJS,高德地图,NodeJS'
               },
               {
                FromDate:'2017.08',
                ToDate:'今',
                DoWhat:'个人微信小程序前端',
                Github:'',
                UseTec:''
               },
               {
                FromDate:'2019.10',
                ToDate:'今',
                DoWhat:'七只企鹅App（前端，服务器，数据库）',
                Github:{
                    Android:'https://github.com/linyangcong/SevenPenguin',
                    Node:'https://github.com/linyangcong/SevenPenguinServer'
                },
                UseTec:'NodeJS,mysql,express,WebView,react-navigation,ES6,react-native-video,react-native-sound,ReactJS,ReactNative,Axios,ant-design,Tab路由,抽屉路由,Stack路由等等'
               },
               {
                FromDate:'2019.12',
                ToDate:'今',
                DoWhat:'H5聊天网页（前端，服务器，数据库）',
                Github:{
                    HTML5:'https://github.com/linyangcong/HeartBeatFont',
                    Node:'https://github.com/linyangcong/HeartBeatServer',
                    desktop:'https://github.com/linyangcong/elec_sayhello'
                },
                UseTec:'Electron,WebView,ES6,ElementUI,axios,express-ws,Vue,vue-router,BabelJS,WebPack,mysql,ws,express等'
               },
               {
                FromDate:'2020.02',
                ToDate:'今',
                DoWhat:'简单的个人简历模版',
                Github:{
                    HTML5:'https://github.com/linyangcong/ElectronVue',
                },
                UseTec:'NodeJS,Webpack,VueJS,BabelJS,ES6,ElementUI'
               },
               
            ],
            ProjectExperience:[
                {
                    FromDate:'2017.11',
                    ToDate:'今',
                    ProjectName:'中山市双向转诊系统(网站前端，桌面端)',
                    UseTec:'Vue,Electron,echart,axios,webpack,ES6,babeljs,node等等',
                    Problem:'--',
                    Resolve:'--'
                },
                {
                    FromDate:'2018.06',
                    ToDate:'今',
                    ProjectName:'中山市计免预约系统(网站前，App、微信 H5网页)',
                    UseTec:'vue,webpack,babel,node,elementui,echart,axios,ES6,express,less,mint-ui等等',
                    Problem:'--',
                    Resolve:'--'
                },
                {
                    FromDate:'2018.08',
                    ToDate:'今',
                    ProjectName:'中山市家医管理平台(网站前端)',
                    UseTec:'babel,vue,webpack,jquery,less,ES6等等',
                    Problem:'--',
                    Resolve:'--'
                },
                {
                    FromDate:'2018.11',
                    ToDate:'今',
                    ProjectName:'健康中山APP以及微信-预约挂号H5网页',
                    UseTec:'vue,axios,jquery,mint-ui,babel,express,less,webpack,ES6等等',
                    Problem:'--',
                    Resolve:'--'
                }, 
            ],
            SelfAssessment:'团队意识，责任心，自学能力强'
        }
    }
]